--CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE INTEGER NOT NULL,
    NOME_RAZAO VARCHAR(120),
    TIPO_PESSOA CHAR(1),
    CPF_CNPJ VARCHAR(14),
    UF CHAR(2),
    DT_CADASTRO TIMESTAMP);
    
ALTER TABLE CLIENTE
ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY (ID_CLIENTE);

--PRODUTO
CREATE TABLE PRODUTO (
    ID_PRODUTO INTEGER NOT NULL,
    DESCRICAO VARCHAR(160),
    NCM VARCHAR(8),
    CFOP_PADRAO VARCHAR(4),
    PRECO_VENDA DECIMAL(15,2));

ALTER TABLE PRODUTO
ADD CONSTRAINT PK_PRODUTO
PRIMARY KEY (ID_PRODUTO);

--PEDIDO
CREATE TABLE PEDIDO (
    ID_PEDIDO INTEGER NOT NULL,
    ID_CLIENTE INTEGER,
    DT_EMISSAO TIMESTAMP,
    STATUS VARCHAR(20),
    TOTAL DECIMAL(15,2));

ALTER TABLE PEDIDO
ADD CONSTRAINT PK_PEDIDO
PRIMARY KEY (ID_PEDIDO);

--PEDIDO_ITEM
CREATE TABLE PEDIDO_ITEM (
    ID_PEDIDO_ITEM INTEGER NOT NULL,
    ID_PEDIDO INTEGER,
    ID_PRODUTO INTEGER,
    QUANTIDADE DECIMAL(15,4),
    VL_UNITARIO DECIMAL(15,2),
    VL_TOTAL DECIMAL(15,2));

ALTER TABLE PEDIDO_ITEM
ADD CONSTRAINT PK_PEDIDO_ITEM
PRIMARY KEY (ID_PEDIDO_ITEM);

--NFE
CREATE TABLE NFE (
    ID_NFE INTEGER NOT NULL,
    ID_PEDIDO INTEGER,
    SERIE INTEGER,
    NUMERO INTEGER,
    STATUS_ATUAL VARCHAR(20),
    CHAVE_ACESSO VARCHAR(44),
    DT_EMISSAO TIMESTAMP,
    CORRIGIR CHAR(1));

ALTER TABLE NFE
ADD CONSTRAINT PK_NFE
PRIMARY KEY (ID_NFE);

--NFE_EVENTO
CREATE TABLE NFE_EVENTO (
    ID_NFE_EVENTO INTEGER NOT NULL,
    ID_NFE INTEGER,
    DT_EVENTO TIMESTAMP,
    STATUS_ANTES VARCHAR(20),
    STATUS_DEPOIS VARCHAR(20),
    MOTIVO VARCHAR(255));

ALTER TABLE NFE_EVENTO
ADD CONSTRAINT PK_NFE_EVENTO
PRIMARY KEY (ID_NFE_EVENTO);

--LOG_EVENTO
CREATE TABLE LOG_EVENTO (
    ID_LOG INTEGER NOT NULL,
    DT_LOG TIMESTAMP,
    ENTIDADE VARCHAR(20),
    ACAO VARCHAR(40),
    MENSAGEM VARCHAR(255));

ALTER TABLE LOG_EVENTO
ADD CONSTRAINT PK_LOG_EVENTO
PRIMARY KEY (ID_LOG);    
